### ISSUE TITLE
Docs: Implement Document folder structure

### ISSUE THREAD

**Issue by SenorMonito** [allinbits/cosmos-cash#140]
## Overview

ADR 002 outlines a proposed documentation structure. This issue is the implementation of those recommendations:

## Tasks

- [ ] Implement folder structure 
- [ ] Move CosmosCashRegs repo to /docs/Explanation/articles
- [ ] Move ADR documents into /docs/Explanation/ADR
